language: rust
rust:
  - nightly
  - beta
  - stable
script:
  - make test
  - cd serde-code-generator && cargo run && diff="$(git diff)" && echo "${diff}" && [[ -z "${diff}" ]]
notifications:
  webhooks: http://build.servo.org:54856/travis
